#=======================================================================
#@V@:Note: File automatically generated by VIDE: (11:11:03 04 Dec 2001) (gcc).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC  	=	gcc

WRES	=	windres

HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=
incDirs	=
LIBS	=	-s 
C_FLAGS	=	-O

SRCS	=\
	$(Src)/bdicnf.c\
	$(Src)/bdidll.c\
	$(Src)/bdisetup.c

EXOBJS	=\
	$(oDir)/bdicnf.o\
	$(oDir)/bdidll.o\
	$(oDir)/bdisetup.o

ALLOBJS	=	$(EXOBJS)
ALLBIN	=	$(Bin)/bdisetup
ALLTGT	=	$(Bin)/bdisetup

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/bdisetup: $(EXOBJS)
	$(CC) -o $(Bin)/bdisetup $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/bdicnf.o : bdicnf.c bdidll.h bdicnf.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/bdidll.o : bdidll.c bdierror.h bdicmd.h bdidll.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/bdisetup.o : bdisetup.c bdierror.h bdicmd.h bdidll.h bdicnf.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
