 
TARGET = beer-process
SRC    =  $(TARGET).c
OBJS   =  $(TARGET).o
CC     =  gcc
CFLAGS = -g3 -W -Wall -std=c99

$(TARGET): $(OBJS)
#beer-process : beer-process.o

#.PHONY: clean

clean:
	$(RM) $(TARGET) $(OBJS)
# 
# TARGET = beer-process
# SRC = $(TARGET).c
# OBJ = $(TARGET).o
# CC = gcc
# CFLAGS = -g3 -W -Wall -std=c99
# 
# $(TARGET): $(OBJ)
# 
# clean:
# 	$(RM) $(TARGET) $(OBJS)
# 	