PLATFORM_RELFLAGS += -fno-strict-aliasing  -fno-common -ffixed-r8 \
	-msoft-float

PLATFORM_CPPFLAGS += -march=armv4
# =========================================================================
#
# Supply options according to compiler version
#
# =========================================================================
PLATFORM_CPPFLAGS +=$(call cc-option,-mapcs-32,-mabi=apcs-gnu)
PLATFORM_RELFLAGS +=$(call cc-option,-mshort-load-bytes,$(call cc-option,-malignment-traps,)) 




.DEFAULT GOAL = clean

name1 := $(lastword $(MAKEFILE_LIST))
     
-include config.mk
     
name2 := $(lastword $(MAKEFILE_LIST))
    
find:
    @echo name1 = $(name1)
    @echo name2 = $(name2)

ifeq (0,${MAKELEVEL})
whoami    := $(shell whoami)
host-type := $(shell arch)
MAKE := ${MAKE} host-type=${host-type} whoami=${whoami}
endif

VERSION = 1
PATCHLEVEL = 1
SUBLEVEL = 0
EXTRAVERSION =
DATALOGGER_VERSION = $(VERSION).$(PATCHLEVEL).$(SUBLEVEL)$(EXTRAVERSION)
VERSION_FILE = $(obj)include/version_autogenerated.h


HOSTARCH := $(shell uname -m | 	sed -e s/i.86/i386/ )
HOSTOS := $(shell uname -s | tr '[:upper:]' '[:lower:]' |  sed -e 's/\(cygwin\).*/cygwin/')

# 'export BUILD_DIR=/tmp/build'
# 'make'
#
# When the above method is not used the local build is performed and
# the object files are placed in the source directory.
#
 